### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-1-Pavlenko** [UMSF-K13-1-Pavlenko/ConsoleApplication1#1]
[K13-1-Pavlenko.docx](https://github.com/UMSF-K13-1-Pavlenko/ConsoleApplication1/files/288292/K13-1-Pavlenko.docx)

**Comment by Smoktii** [comment]
Установите меня как исполнителя ишью

**Comment by UMSF-K13-1-Pavlenko** [comment]
есть

**Comment by Smoktii** [comment]
ок
